# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b432611e4d1ba05434b6b5d2235e9f0c33736ab6b0175d77fc95e6a31693b3b1fc81c7f3c23253cd0b1b3f960ed576e717397152d09be1a05496a0ee43fafc

test:
  secret_key_base: 239354531c5de945026910acfd9afd270cf10466898ff0018e5e2cbc9b6798814f80ca781227fea75491b919f2332dedd0ff74d3d7b78a6d550e6f00c4b82935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
